apiVersion: v1
kind: Service
metadata:
  name: custom-api
spec:
  selector:
    app: custom-api
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5555
    nodePort: 30634
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-api
spec:
  selector:
    matchLabels:
      app: custom-api
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-api
    spec:
      imagePullSecrets: []
      containers:
      - name: custom-api
        image: eclipseaerios/iota-messages-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5555
